# railway.toml

[backend]
root_dir = "backend"
start = "npm start"

[backend.env]
MONGODB_URI = "mongodb+srv://tudorriva:glopus123@clusterpotimetech.affminn.mongodb.net/?retryWrites=true&w=majority&appName=ClusterPOTimeTech"
PORT = "5000"
NODE_ENV = "development"
JWT_SECRET = "platacuora-super-secret-key-for-authentication-2025"
JWT_EXPIRES_IN = "365d"
GOOGLE_CLIENT_ID = "415628246190-mftabnui4s3gajaa5mrtl42n8g48bbub.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_CALLBACK_URL = "http://localhost:5000/api/auth/google/callback"
FRONTEND_URL = "http://localhost:4200"

[frontend]
root_dir = "frontend"
start = "ng serve --host 0.0.0.0 --port 80"

[frontend.env]
# variabile de mediu pentru frontend dacă ai nevoie
